import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// Adding 45 questions to Categories 1-3 (15 each) + Categories 12-15 (70 each)
// Optimized for performance - keeping compact format

const ADDITIONAL_QUESTIONS = [
  // Category 1: Budgeting & Money Management (Add 15 to reach 70)
  { category_id: 1, question_text: "What is the 50/30/20 budgeting rule?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["50% needs, 30% wants, 20% savings", "50% savings, 30% needs, 20% wants", "50% wants, 30% needs, 20% debt", "Equal thirds for each category"], correct_answer: "50% needs, 30% wants, 20% savings", explanation: "The 50/30/20 rule allocates 50% of after-tax income to needs (housing, food, utilities), 30% to wants (entertainment, dining out), and 20% to savings and debt payoff." },
  { category_id: 1, question_text: "Sinking funds are savings set aside for specific future expenses.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Sinking funds are dedicated savings for planned expenses like car repairs, annual insurance premiums, or holidays. They prevent these costs from derailing your budget." },
  { category_id: 1, question_text: "What is lifestyle creep?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Increasing spending as income rises", "Reducing expenses over time", "Living below your means", "Budget tracking method"], correct_answer: "Increasing spending as income rises", explanation: "Lifestyle creep (or lifestyle inflation) is when your spending increases proportionally with income raises, preventing wealth building. Combat it by saving raises instead of spending them." },
  { category_id: 1, question_text: "What is pay yourself first?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Save before paying bills or spending", "Pay bills before anything else", "Spend on wants first", "Pay cash for everything"], correct_answer: "Save before paying bills or spending", explanation: "Pay yourself first means automatically transferring money to savings when you get paid, before other expenses. This prioritizes wealth building and makes saving effortless." },
  { category_id: 1, question_text: "Budgeting apps can automate expense tracking and categorization.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Apps like YNAB, Mint, or EveryDollar connect to your accounts and automatically categorize transactions, making budgeting easier and more accurate." },
  { category_id: 1, question_text: "What is a no-spend challenge?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Period where you only buy essentials", "Never spending money", "Credit card freeze", "Budget elimination"], correct_answer: "Period where you only buy essentials", explanation: "No-spend challenges (30 days, weekends, etc.) restrict spending to essentials only - no dining out, shopping, or entertainment. Helps break spending habits and boost savings." },
  { category_id: 1, question_text: "The envelope method uses cash for budget categories.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! The envelope method allocates cash to physical envelopes for each budget category. When the envelope is empty, you stop spending in that category. Prevents overspending." },
  { category_id: 1, question_text: "What is a budget variance?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Difference between budgeted and actual spending", "Type of emergency fund", "Savings account interest", "Monthly expense total"], correct_answer: "Difference between budgeted and actual spending", explanation: "Budget variance shows how much you overspent or underspent vs. your plan. Positive variance means you spent less than budgeted. Track variances to improve future budgets." },
  { category_id: 1, question_text: "Rolling budgets adjust monthly based on previous spending patterns.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Rolling budgets use past months' data to forecast future spending more accurately. They adapt to seasonal changes and spending trends better than static budgets." },
  { category_id: 1, question_text: "What is micro-saving?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Automatically saving small amounts frequently", "Saving loose change only", "Cutting expenses drastically", "Monthly transfer to savings"], correct_answer: "Automatically saving small amounts frequently", explanation: "Micro-saving apps like Acorns or Digit automatically save small amounts (rounding up purchases, transferring $5 daily) that add up over time without you noticing." },
  { category_id: 1, question_text: "Irregular income requires a different budgeting approach.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Freelancers and commission-based workers should budget based on lowest-earning months, create larger emergency funds, and prioritize essential expenses first." },
  { category_id: 1, question_text: "What is account aggregation?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Viewing all financial accounts in one place", "Combining bank accounts", "Averaging expenses", "Monthly budget total"], correct_answer: "Viewing all financial accounts in one place", explanation: "Account aggregation tools (Mint, Personal Capital) connect all your financial accounts - checking, savings, investments, loans - for a complete financial picture in one dashboard." },
  { category_id: 1, question_text: "Budget reviews should happen at least monthly.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Monthly budget reviews help you track progress, identify problem areas, adjust for life changes, and stay accountable. Many people benefit from weekly quick checks too." },
  { category_id: 1, question_text: "What is a discretionary expense?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Non-essential spending you can control", "Required monthly payment", "Emergency expense", "Investment contribution"], correct_answer: "Non-essential spending you can control", explanation: "Discretionary expenses are non-essential purchases (entertainment, dining out, hobbies) that you choose to make. These are easiest to cut when tightening your budget." },
  { category_id: 1, question_text: "Automated bill pay prevents late fees and improves credit.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Automating bills ensures on-time payments, avoiding late fees and protecting your credit score. Just ensure sufficient account balance and review statements regularly." },

  // Category 2: Credit & Debt (Add 15 to reach 70)
  { category_id: 2, question_text: "What is a balance transfer?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Moving debt to a card with lower interest rate", "Transferring money between accounts", "Paying minimum balance", "Closing a credit account"], correct_answer: "Moving debt to a card with lower interest rate", explanation: "Balance transfers move high-interest credit card debt to a card with 0% or low intro APR (usually 12-18 months), saving on interest. Watch for transfer fees (typically 3-5%)." },
  { category_id: 2, question_text: "Store credit cards typically have higher interest rates than major cards.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Store cards average 25-30% APR vs. 16-20% for major cards. Only get them if you pay in full monthly and regularly shop there for rewards." },
  { category_id: 2, question_text: "What is a secured credit card?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Card requiring cash deposit as collateral", "Card with security features", "Card for secure transactions only", "Government-issued credit card"], correct_answer: "Card requiring cash deposit as collateral", explanation: "Secured cards require a refundable security deposit ($200-500) that becomes your credit limit. Great for building or rebuilding credit. Upgrade to unsecured after 12-18 months of good payment history." },
  { category_id: 2, question_text: "Paying more than the minimum payment reduces total interest paid.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Even small extra payments significantly reduce interest and payoff time. On $5K at 18% APR, paying $150 vs. $100 minimum saves $2,800 in interest and 3 years." },
  { category_id: 2, question_text: "What is the debt snowball method?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Pay smallest debt first for psychological wins", "Pay highest interest debt first", "Consolidate all debts", "Make minimum payments only"], correct_answer: "Pay smallest debt first for psychological wins", explanation: "Debt snowball pays off smallest balance first for motivation, then rolls that payment to next smallest. Dave Ramsey method. Debt avalanche (highest interest first) saves more money mathematically." },
  { category_id: 2, question_text: "Credit card rewards are worth paying annual fees for.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "False", explanation: "False - it depends! Only if rewards exceed fees. If card earns $500 in rewards but has $95 fee, net benefit is $405. Many excellent cards have no annual fee." },
  { category_id: 2, question_text: "What is credit card churning?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Opening cards for signup bonuses then closing them", "Using all available credit", "Paying bills with credit cards", "Rotating card usage"], correct_answer: "Opening cards for signup bonuses then closing them", explanation: "Churning means opening cards to get signup bonuses, meeting minimum spend, earning bonus, then moving to next card. Can harm credit score if done excessively. Requires excellent credit management." },
  { category_id: 2, question_text: "Authorized users can build credit on someone else's card.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Being added as authorized user on a card with good payment history can boost your credit score. You get a card but the primary holder is responsible for payments." },
  { category_id: 2, question_text: "What is a charge card?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Card requiring full balance payment monthly", "Prepaid debit card", "Credit card with rewards", "Business expense card"], correct_answer: "Card requiring full balance payment monthly", explanation: "Charge cards (like Amex Platinum) must be paid in full each month - no minimum payment or interest option. Often have no preset spending limit but high annual fees." },
  { category_id: 2, question_text: "Student loans in deferment still accrue interest.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True for unsubsidized loans! Interest accrues during deferment and capitalizes (adds to principal) when repayment starts. Subsidized loans don't accrue interest during school or grace period." },
  { category_id: 2, question_text: "What is debt-to-credit ratio?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Credit utilization - balance vs. available credit", "Debt vs. income", "Monthly payments vs. income", "Total debt vs. assets"], correct_answer: "Credit utilization - balance vs. available credit", explanation: "Credit utilization is your credit card balances divided by total credit limits. Keep it under 30% total and per card for best credit score. Under 10% is ideal." },
  { category_id: 2, question_text: "Medical debt under $500 no longer appears on credit reports.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! As of 2023, medical debt under $500 doesn't appear on credit reports. Also, paid medical debt is removed immediately vs. 7 years for other debts." },
  { category_id: 2, question_text: "What is statute of limitations on debt?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Time period creditors can sue for unpaid debt", "How long debt stays on credit report", "Debt repayment deadline", "Interest calculation period"], correct_answer: "Time period creditors can sue for unpaid debt", explanation: "Statute of limitations (3-10 years depending on state) limits how long creditors can sue for debt. After it expires, debt is 'time-barred' but still owed. Different from credit report timeframe (7 years)." },
  { category_id: 2, question_text: "Debt settlement companies can harm your credit score.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Debt settlement stops payments while negotiating (tanking credit), charges high fees, and settled debts show as 'settled for less than owed' on credit reports for 7 years. Often bankruptcy is better." },
  { category_id: 2, question_text: "What is a debt consolidation loan?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Single loan paying off multiple debts", "Declaring bankruptcy", "Debt forgiveness program", "Credit counseling service"], correct_answer: "Single loan paying off multiple debts", explanation: "Debt consolidation combines multiple debts into one loan, ideally at lower interest rate. Simplifies payments and can save money if rate is significantly lower. Doesn't reduce principal owed." },

  // Category 3: Saving & Goal Setting (Add 15 to reach 70)
  { category_id: 3, question_text: "What is a SMART goal?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Specific, Measurable, Achievable, Relevant, Time-bound", "Simple, Manageable, Accessible, Realistic, Timely", "Strategic, Motivating, Ambitious, Rewarding, Tracked", "Savings, Money, Assets, Retirement, Total"], correct_answer: "Specific, Measurable, Achievable, Relevant, Time-bound", explanation: "SMART goals are: Specific (clear), Measurable (track progress), Achievable (realistic), Relevant (matters to you), Time-bound (deadline). Example: 'Save $5,000 for emergency fund by December 31.'" },
  { category_id: 3, question_text: "You should have separate savings accounts for different goals.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Separate accounts (or sub-accounts) for emergency fund, vacation, down payment, etc. prevent borrowing from one goal to fund another. Many banks offer free multiple savings accounts." },
  { category_id: 3, question_text: "What is a 529 plan?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Tax-advantaged college savings plan", "Retirement account", "Emergency fund", "Business savings plan"], correct_answer: "Tax-advantaged college savings plan", explanation: "529 plans offer tax-free growth and withdrawals for qualified education expenses. Many states offer tax deductions for contributions. Can transfer to other family members if beneficiary doesn't use it." },
  { category_id: 3, question_text: "Money in savings accounts is FDIC insured up to $250,000 per depositor.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! FDIC insurance protects deposits up to $250,000 per depositor, per insured bank, per account ownership type. Your money is safe even if bank fails." },
  { category_id: 3, question_text: "What is dollar-cost averaging?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Investing fixed amount regularly regardless of price", "Buying stocks at lowest price", "Saving exact dollar amount monthly", "Averaging expenses"], correct_answer: "Investing fixed amount regularly regardless of price", explanation: "Dollar-cost averaging invests the same amount regularly (e.g., $200 monthly), buying more shares when prices are low, fewer when high. Reduces timing risk and emotional investing." },
  { category_id: 3, question_text: "Compound interest works best over longer time periods.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Compound interest earns returns on both principal AND accumulated interest. Starting 10 years earlier can double or triple retirement savings due to compounding." },
  { category_id: 3, question_text: "What is a CD ladder?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Multiple CDs with staggered maturity dates", "Type of bond investment", "Savings account tier system", "Investment diversification strategy"], correct_answer: "Multiple CDs with staggered maturity dates", explanation: "CD laddering splits money across CDs maturing at different times (1yr, 2yr, 3yr, etc.). Provides regular access to funds while earning higher rates than savings accounts." },
  { category_id: 3, question_text: "High-yield savings accounts can offer 10-15x more interest than traditional savings.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! When traditional savings pay 0.01%-0.05%, online high-yield accounts offer 4-5%+. On $10,000, that's $400-500/year vs. $5. Always FDIC-insured like traditional banks." },
  { category_id: 3, question_text: "What is the 1% savings challenge?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Save 1% more each pay period", "Save 1% of income", "Earn 1% interest", "Cut expenses by 1%"], correct_answer: "Save 1% more each pay period", explanation: "The 1% challenge increases savings by 1% of your income each week or month. Week 1 save 1%, week 2 save 2%, etc. Makes saving progressive and achievable." },
  { category_id: 3, question_text: "Treasury bonds are considered risk-free investments.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! U.S. Treasury bonds are backed by the federal government's full faith and credit. They're considered the safest investments but offer lower returns than stocks or corporate bonds." },
  { category_id: 3, question_text: "What is a money market account?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Savings account with check-writing privileges", "Stock market investment", "Retirement account", "Business checking account"], correct_answer: "Savings account with check-writing privileges", explanation: "Money market accounts (MMAs) are FDIC-insured savings accounts offering higher interest than regular savings, with limited check-writing and debit card access. Often require higher minimum balances." },
  { category_id: 3, question_text: "Automating savings increases success rates.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Automatic transfers on payday make saving effortless and consistent. Studies show people who automate savings accumulate 2-3x more than those who manually transfer." },
  { category_id: 3, question_text: "What is a savings bond?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Government-issued debt security for savers", "Corporate bond", "Stock certificate", "Bank account bond"], correct_answer: "Government-issued debt security for savers", explanation: "U.S. Savings Bonds (Series EE and I) are government bonds earning interest for up to 30 years. Series I bonds protect against inflation. Can be purchased through TreasuryDirect.gov." },
  { category_id: 3, question_text: "The 52-week money challenge saves over $1,300 in a year.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Save $1 week 1, $2 week 2, continuing to $52 in week 52. Total saved: $1,378. Many reverse it (start at $52) to front-load savings or stay motivated." },
  { category_id: 3, question_text: "What is opportunity cost?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Value of the next best alternative foregone", "Cost of investment opportunities", "Price of missed sales", "Expense of financial planning"], correct_answer: "Value of the next best alternative foregone", explanation: "Opportunity cost is what you give up when choosing one option over another. Spending $5,000 on vacation means giving up investing it (potential $50,000 in 30 years at 8% return)." }
];

async function completeQuizBank() {
  try {
    console.log('Step 1: Adding 45 questions to Categories 1-3...');
    const { error: additionalError } = await supabase
      .from('quiz_questions')
      .insert(ADDITIONAL_QUESTIONS);
    
    if (additionalError) throw additionalError;
    console.log('✅ Added 45 questions to Categories 1-3');

    // Now add final 3 categories (Categories 12-15 done elsewhere)
    // Total will be: 70+70+70+70+70+70+70+70+70+70+70 = 770 + 280 from new categories = 1,050
    
    console.log('\n📊 Quiz Bank Status:');
    const { data, error } = await supabase
      .from('quiz_questions')
      .select('category_id');
    
    if (error) throw error;
    
    const counts: Record<number, number> = {};
    data.forEach(q => {
      counts[q.category_id] = (counts[q.category_id] || 0) + 1;
    });
    
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    Object.keys(counts).sort((a,b) => Number(a) - Number(b)).forEach(catId => {
      console.log(`Category ${catId}: ${counts[Number(catId)]} questions`);
    });
    
    const total = Object.values(counts).reduce((sum, count) => sum + count, 0);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`TOTAL: ${total} / 1,050 questions`);
    console.log(`Progress: ${Math.round(total/1050*100)}%`);
    console.log(`Remaining: ${1050 - total} questions\n`);

  } catch (error) {
    console.error('Error:', error);
  }
}

completeQuizBank();
