import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!
const supabase = createClient(supabaseUrl, supabaseKey)

// CATEGORY 12: Estate Planning (70 questions)
const CATEGORY_12_ESTATE = [
  // Beginner (25)
  { category_id: 12, question_text: "What is a will?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["A legal document directing asset distribution after death", "Life insurance policy", "Retirement account", "Bank account"], correct_answer: "A legal document directing asset distribution after death", explanation: "A will is a legal document specifying how you want your assets distributed after you die. Without a will, state law determines who gets what." },
  { category_id: 12, question_text: "Everyone needs a will, regardless of age or wealth.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Anyone over 18 should have a will, especially parents of minor children. It ensures your wishes are followed and simplifies the process for loved ones." },
  { category_id: 12, question_text: "What is a beneficiary?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Person who receives assets from your estate", "Estate planning lawyer", "Executor of will", "Tax collector"], correct_answer: "Person who receives assets from your estate", explanation: "A beneficiary is someone named to receive assets from your will, life insurance, retirement accounts, or trust. Keep beneficiary designations updated." },
  { category_id: 12, question_text: "What is an executor?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Person who carries out will instructions", "Judge overseeing estate", "Beneficiary of estate", "Tax preparer"], correct_answer: "Person who carries out will instructions", explanation: "An executor (or personal representative) manages your estate after death - paying debts, filing taxes, distributing assets per your will. Choose someone trustworthy and organized." },
  { category_id: 12, question_text: "Life insurance proceeds are generally tax-free to beneficiaries.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Life insurance death benefits are typically income tax-free to beneficiaries. However, they may be subject to estate tax if your estate is large enough." },
  { category_id: 12, question_text: "What is probate?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Legal process of settling an estate", "Type of will", "Inheritance tax", "Life insurance claim"], correct_answer: "Legal process of settling an estate", explanation: "Probate is the court-supervised process of validating a will, paying debts, and distributing assets. It can be lengthy and costly, which is why some people use trusts to avoid it." },
  { category_id: 12, question_text: "Beneficiary designations override what's in your will.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Assets with beneficiary designations (life insurance, 401k, IRA) go directly to named beneficiaries, bypassing your will. Review and update these regularly." },
  { category_id: 12, question_text: "What is a power of attorney?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Legal authority to act on someone's behalf", "Type of lawyer", "Court order", "Will substitute"], correct_answer: "Legal authority to act on someone's behalf", explanation: "A power of attorney (POA) authorizes someone to make financial or medical decisions for you if you're incapacitated. Essential estate planning document." },
  { category_id: 12, question_text: "What is a living will?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Document stating end-of-life medical wishes", "Will that's currently active", "Trust for living expenses", "Life insurance policy"], correct_answer: "Document stating end-of-life medical wishes", explanation: "A living will (advance directive) specifies your wishes for life-sustaining medical treatment if you can't communicate. Different from a regular will." },
  { category_id: 12, question_text: "You should review and update your will every 3-5 years.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Review your will every 3-5 years or after major life events (marriage, divorce, birth, death, large asset changes). Laws and circumstances change." },
  { category_id: 12, question_text: "What is a healthcare proxy?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Person authorized to make medical decisions for you", "Medical insurance policy", "Hospital administrator", "Doctor's assistant"], correct_answer: "Person authorized to make medical decisions for you", explanation: "A healthcare proxy (or medical POA) is someone you designate to make medical decisions if you're unable. Choose someone who knows your wishes and can handle difficult decisions." },
  { category_id: 12, question_text: "Minor children can't inherit assets directly.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Minors can't legally control assets. If you leave assets to minors without a trust or guardian designation, courts will appoint someone to manage until they're 18." },
  { category_id: 12, question_text: "What is a guardian?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Person who cares for minor children if parents die", "Estate lawyer", "Trustee", "Executor"], correct_answer: "Person who cares for minor children if parents die", explanation: "A guardian is the person you name in your will to raise your minor children if you die. Without designation, courts decide who raises your kids." },
  { category_id: 12, question_text: "What is estate tax?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Tax on assets transferred at death", "Annual property tax", "Income tax on inheritance", "Sales tax"], correct_answer: "Tax on assets transferred at death", explanation: "Estate tax is a federal tax on the transfer of assets at death. In 2024, only estates over $13.61M are taxed. Some states also have estate or inheritance taxes." },
  { category_id: 12, question_text: "Digital assets (social media, crypto) should be included in estate planning.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Include digital assets in your estate plan - passwords, cryptocurrency, social media accounts, online businesses, photos. Provide access instructions to your executor." },
  { category_id: 12, question_text: "What is a trust?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Legal entity holding assets for beneficiaries", "Type of will", "Bank account", "Insurance policy"], correct_answer: "Legal entity holding assets for beneficiaries", explanation: "A trust is a legal arrangement where a trustee holds and manages assets for beneficiaries. Can avoid probate, provide control, and offer tax benefits." },
  { category_id: 12, question_text: "Joint accounts automatically pass to the surviving owner.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Joint accounts with right of survivorship automatically transfer to the surviving owner, bypassing probate and your will. Be careful who you add as joint owner." },
  { category_id: 12, question_text: "What does 'per stirpes' mean?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Assets go to descendants if beneficiary predeceases you", "Equal distribution among beneficiaries", "Spouse gets everything", "Charity receives remainder"], correct_answer: "Assets go to descendants if beneficiary predeceases you", explanation: "Per stirpes means if a beneficiary dies before you, their share goes to their descendants. Example: If your daughter predeceases you, her children get her share." },
  { category_id: 12, question_text: "What is probate?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Court process of administering a deceased person's estate", "Type of trust", "Tax on inheritance", "Life insurance policy"], correct_answer: "Court process of administering a deceased person's estate", explanation: "Probate validates the will, inventories assets, pays debts and taxes, and distributes remaining assets. Can take months to years and costs 3-7% of estate value." },
  { category_id: 12, question_text: "Most states have simplified probate for small estates.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Many states offer expedited probate for estates under a threshold (often $50K-$200K). Requirements vary by state." },
  { category_id: 12, question_text: "What is a revocable trust?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Trust that can be changed or cancelled while alive", "Trust that cannot be changed", "Retirement account", "Will substitute"], correct_answer: "Trust that can be changed or cancelled while alive", explanation: "A revocable (living) trust can be modified or dissolved while you're alive. Avoids probate and provides privacy but offers no asset protection or tax benefits during life." },
  { category_id: 12, question_text: "You need a lawyer to create a valid will.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "False", explanation: "False! While advisable, many states accept DIY wills if properly signed and witnessed. Online services like LegalZoom or Nolo can help. Complex estates should use attorneys." },
  { category_id: 12, question_text: "What is a letter of instruction?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Informal document guiding executor on personal wishes", "Legal requirement for wills", "Court order", "Tax form"], correct_answer: "Informal document guiding executor on personal wishes", explanation: "A letter of instruction is a non-legal document providing guidance on funeral wishes, account locations, passwords, pet care, sentimental item distribution. Helps executor immensely." },
  { category_id: 12, question_text: "What are death taxes?", question_type: "multiple_choice", difficulty_level: "beginner", options: ["Estate and inheritance taxes on transferred wealth", "Income taxes for deceased person's final year", "Funeral expenses", "Medical bills"], correct_answer: "Estate and inheritance taxes on transferred wealth", explanation: "Death taxes include federal estate tax (on estates over $13.61M in 2024) and some state estate or inheritance taxes. Most people don't pay federal estate tax." },
  { category_id: 12, question_text: "Charitable donations in your will can reduce estate taxes.", question_type: "true_false", difficulty_level: "beginner", options: ["True", "False"], correct_answer: "True", explanation: "True! Charitable bequests are deductible from your taxable estate, reducing estate taxes. Can leave a legacy while lowering tax burden on heirs." },

  // Intermediate (25)
  { category_id: 12, question_text: "What is the difference between a revocable and irrevocable trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Revocable can be changed; irrevocable cannot", "Revocable avoids taxes; irrevocable doesn't", "No practical difference", "Irrevocable is cheaper"], correct_answer: "Revocable can be changed; irrevocable cannot", explanation: "Revocable trusts can be modified or dissolved; irrevocable trusts cannot (or require court approval). Irrevocable trusts remove assets from your estate for tax/protection purposes." },
  { category_id: 12, question_text: "What is a testamentary trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Trust created through your will, effective at death", "Trust created while alive", "Retirement account", "Insurance policy"], correct_answer: "Trust created through your will, effective at death", explanation: "A testamentary trust is established by your will and takes effect when you die. Often used for minor children or special needs beneficiaries. Goes through probate." },
  { category_id: 12, question_text: "Assets in an irrevocable trust avoid estate taxes.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Properly structured irrevocable trusts remove assets from your taxable estate. You lose control, but heirs may pay less tax. Consult an estate attorney." },
  { category_id: 12, question_text: "What is a special needs trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Trust preserving government benefits for disabled beneficiary", "Trust for medical expenses", "Retirement trust", "Charitable trust"], correct_answer: "Trust preserving government benefits for disabled beneficiary", explanation: "Special needs trusts provide for disabled individuals without disqualifying them from SSI, Medicaid, or other means-tested benefits. Essential for disabled dependents." },
  { category_id: 12, question_text: "What is the annual gift tax exclusion?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["$18,000 per person per year (2024)", "$10,000 per person per year", "$50,000 per person per year", "$5,000 per person per year"], correct_answer: "$18,000 per person per year (2024)", explanation: "You can gift $18,000 per person per year (2024) without gift tax or reporting. Married couples can give $36,000 together. Exceeding this uses your lifetime exemption." },
  { category_id: 12, question_text: "Gifting during life can reduce your taxable estate.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Strategic gifting removes assets from your estate. Use annual exclusions, pay medical/education expenses directly, or fund 529 plans to reduce estate size legally." },
  { category_id: 12, question_text: "What is a QTIP trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Qualified Terminable Interest Property trust for surviving spouse", "Retirement account for spouse", "Life insurance policy", "Charitable trust"], correct_answer: "Qualified Terminable Interest Property trust for surviving spouse", explanation: "QTIP trusts provide income to surviving spouse while preserving principal for children from previous marriage. Common in blended families. Qualifies for marital deduction." },
  { category_id: 12, question_text: "What is portability in estate tax?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Unused estate tax exemption transfers to surviving spouse", "Moving assets between states", "Transferring property ownership", "Converting assets to cash"], correct_answer: "Unused estate tax exemption transfers to surviving spouse", explanation: "Portability allows surviving spouse to use deceased spouse's unused estate tax exemption. Must file estate tax return (706) within 9 months to elect portability." },
  { category_id: 12, question_text: "A pour-over will transfers remaining assets into a trust.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! A pour-over will 'catches' any assets not already in your trust and pours them into the trust at death. Backup for trust-based estate plans." },
  { category_id: 12, question_text: "What is a bypass trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Trust minimizing estate taxes for wealthy couples", "Trust avoiding probate", "Trust for minor children", "Revocable living trust"], correct_answer: "Trust minimizing estate taxes for wealthy couples", explanation: "Bypass (credit shelter) trusts use both spouses' estate tax exemptions, potentially saving millions in taxes. Less critical now due to portability and high exemptions." },
  { category_id: 12, question_text: "What is a spendthrift clause?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Trust provision protecting beneficiary from creditors and themselves", "Budget requirement", "Spending limit", "Payment schedule"], correct_answer: "Trust provision protecting beneficiary from creditors and themselves", explanation: "Spendthrift clauses prevent beneficiaries from pledging trust assets to creditors and limit trustee distributions, protecting irresponsible beneficiaries from themselves." },
  { category_id: 12, question_text: "Retirement accounts should not be left to trusts as beneficiaries.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "False", explanation: "False! Trusts can be IRA beneficiaries if properly structured (see-through trusts). Useful for control, creditor protection, or blended families. Requires expert setup." },
  { category_id: 12, question_text: "What is a generation-skipping transfer tax?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Tax on transfers to grandchildren or later generations", "Tax on annual gifts", "Income tax on inheritance", "Property tax"], correct_answer: "Tax on transfers to grandchildren or later generations", explanation: "GST tax (40%) applies to transfers skipping a generation (to grandchildren). Has same exemption as estate tax ($13.61M in 2024). Prevents wealthy families from avoiding taxes." },
  { category_id: 12, question_text: "What is a Crummey power?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Beneficiary's right to withdraw trust contributions for limited time", "Power of attorney", "Trust amendment right", "Executor authority"], correct_answer: "Beneficiary's right to withdraw trust contributions for limited time", explanation: "Crummey powers give beneficiaries temporary withdrawal rights (usually 30 days) for trust contributions, qualifying gifts for annual exclusion. Named after Crummey case." },
  { category_id: 12, question_text: "Life insurance owned by irrevocable trust avoids estate taxes.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Irrevocable Life Insurance Trusts (ILITs) remove policy proceeds from taxable estate. You can't be owner, but trust provides liquidity for estate taxes and heirs." },
  { category_id: 12, question_text: "What is a charitable remainder trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Trust paying income to you, remainder to charity", "Trust only for charities", "Donation tax credit", "Non-profit organization"], correct_answer: "Trust paying income to you, remainder to charity", explanation: "CRTs pay income to you (or beneficiaries) for term/life, then remaining assets go to charity. Provides income tax deduction, avoids capital gains, reduces estate taxes." },
  { category_id: 12, question_text: "What is step-up in basis?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Assets' cost basis resets to value at death", "Annual increase in asset value", "Depreciation adjustment", "Tax increase"], correct_answer: "Assets' cost basis resets to value at death", explanation: "Step-up in basis resets inherited asset cost basis to fair market value at death, eliminating capital gains tax on appreciation during decedent's life. Huge tax benefit." },
  { category_id: 12, question_text: "Community property states treat marital assets differently than common law states.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! In 9 community property states, spouses own marital assets 50/50. Both halves get step-up in basis at first death. Common law states require asset titling for ownership." },
  { category_id: 12, question_text: "What is a dynasty trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Multi-generational trust avoiding estate taxes for decades", "Family business trust", "Revocable trust", "Short-term trust"], correct_answer: "Multi-generational trust avoiding estate taxes for decades", explanation: "Dynasty trusts last multiple generations (even perpetually in some states), avoiding estate taxes at each generation. Uses GST exemption. Popular for ultra-wealthy families." },
  { category_id: 12, question_text: "What is a disclaimer?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Refusing an inheritance to pass it to alternate beneficiary", "Estate lawsuit", "Trust amendment", "Will contest"], correct_answer: "Refusing an inheritance to pass it to alternate beneficiary", explanation: "A qualified disclaimer lets beneficiaries refuse inheritance, passing it to contingent beneficiaries. Must disclaim within 9 months without having received benefits. Tax planning tool." },
  { category_id: 12, question_text: "Trusts must file annual income tax returns (Form 1041).", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Irrevocable trusts and testamentary trusts file Form 1041 and pay taxes on undistributed income. Revocable trusts file under grantor's SSN while grantor is alive." },
  { category_id: 12, question_text: "What is a living trust?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Revocable trust created during lifetime", "Will substitute only", "Trust only active after death", "Type of life insurance"], correct_answer: "Revocable trust created during lifetime", explanation: "Living trusts are created while alive, usually revocable. You transfer assets to trust, serve as trustee, and name successor for incapacity/death. Avoids probate." },
  { category_id: 12, question_text: "What are TOD and POD accounts?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["Transfer/Payable on Death - assets pass to named beneficiary", "Types of trusts", "Retirement accounts", "Insurance policies"], correct_answer: "Transfer/Payable on Death - assets pass to named beneficiary", explanation: "TOD (transfer on death) for securities and POD (payable on death) for bank accounts automatically transfer to named beneficiary, avoiding probate. Simple probate alternative." },
  { category_id: 12, question_text: "Funeral expenses are paid from the estate before distribution.", question_type: "true_false", difficulty_level: "intermediate", options: ["True", "False"], correct_answer: "True", explanation: "True! Estate debts including funeral costs, final medical bills, taxes, and administration expenses are paid before beneficiaries receive anything. Plan for 3-7% of estate value in costs." },
  { category_id: 12, question_text: "What is intestate succession?", question_type: "multiple_choice", difficulty_level: "intermediate", options: ["State law determining asset distribution without will", "Type of trust", "Tax on inheritance", "Probate process"], correct_answer: "State law determining asset distribution without will", explanation: "If you die without a will (intestate), state law dictates who gets your assets - usually spouse and children. May not match your wishes. Always have a will." },

  // Advanced (20)
  { category_id: 12, question_text: "What is a GRAT?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Grantor Retained Annuity Trust - transfers appreciation gift-tax-free", "Type of retirement account", "Charitable trust", "Life insurance policy"], correct_answer: "Grantor Retained Annuity Trust - transfers appreciation gift-tax-free", explanation: "GRATs transfer appreciating assets to beneficiaries with minimal gift tax. You receive annuity payments; remaining appreciation passes tax-free. Effective for rapidly appreciating assets." },
  { category_id: 12, question_text: "What is an ILIT?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Irrevocable Life Insurance Trust - removes insurance from estate", "Living trust with insurance", "Retirement trust", "Revocable insurance trust"], correct_answer: "Irrevocable Life Insurance Trust - removes insurance from estate", explanation: "ILITs own life insurance policies, removing proceeds from taxable estate. Provides liquidity for estate taxes and heirs without increasing estate tax. Must be irrevocable." },
  { category_id: 12, question_text: "The 3-year rule can pull life insurance back into your estate.", question_type: "true_false", difficulty_level: "advanced", options: ["True", "False"], correct_answer: "True", explanation: "True! If you transfer existing life insurance to ILIT within 3 years of death, proceeds are included in estate. Always have ILIT purchase policy directly to avoid this." },
  { category_id: 12, question_text: "What is a SLAT?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Spousal Lifetime Access Trust - irrevocable gift with indirect access", "Retirement trust for spouse", "Joint revocable trust", "Life insurance trust"], correct_answer: "Spousal Lifetime Access Trust - irrevocable gift with indirect access", explanation: "SLATs let you make irrevocable gifts (removing from estate) while benefiting spouse during life. Locks in high exemptions. Risk: divorce or spouse's death eliminates access." },
  { category_id: 12, question_text: "What is a QPRT?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Qualified Personal Residence Trust - transfers home at reduced gift tax", "Trust for rental properties", "Retirement home trust", "Revocable living trust"], correct_answer: "Qualified Personal Residence Trust - transfers home at reduced gift tax", explanation: "QPRTs transfer your residence to beneficiaries at discounted gift tax value. You retain right to live there for term. If you die during term, it's back in estate." },
  { category_id: 12, question_text: "Clawback provisions may affect large gifts made under high exemptions.", question_type: "true_false", difficulty_level: "advanced", options: ["True", "False"], correct_answer: "False", explanation: "False! Treasury regulations protect against clawback. If you make gifts under high exemption and it later drops, you won't be penalized. Use exemption while high." },
  { category_id: 12, question_text: "What is a charitable lead trust?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Trust paying charity first, remainder to heirs", "Trust only for charities", "Retirement account for charity", "Donation matching program"], correct_answer: "Trust paying charity first, remainder to heirs", explanation: "CLTs pay income to charity for term, then assets go to heirs at reduced gift/estate tax. Opposite of CRT. Good for highly appreciated assets and reducing estate taxes." },
  { category_id: 12, question_text: "What is a defective grantor trust?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Intentionally defective for income tax but not estate tax", "Incorrectly drafted trust", "Trust with errors", "Invalid trust"], correct_answer: "Intentionally defective for income tax but not estate tax", explanation: "Intentionally Defective Grantor Trusts are irrevocable for estate tax (assets removed) but grantor pays income tax (assets grow faster). Advanced wealth transfer technique." },
  { category_id: 12, question_text: "Basis consistency rules require reporting step-up basis to IRS.", question_type: "true_false", difficulty_level: "advanced", options: ["True", "False"], correct_answer: "True", explanation: "True! Executors must report asset basis to IRS (Form 8971) and beneficiaries. Prevents beneficiaries from overstating basis. Required for estates filing Form 706." },
  { category_id: 12, question_text: "What is a Delaware tax trap?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Trust design causing unexpected GST tax", "State inheritance tax", "Audit trigger", "Probate requirement"], correct_answer: "Trust design causing unexpected GST tax", explanation: "Delaware tax trap occurs when trust terms create a taxable event for GST purposes. Named after Delaware statute but applies everywhere. Avoid with careful trust drafting." },
  { category_id: 12, question_text: "What is a self-settled asset protection trust?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Trust where grantor is beneficiary, protected from creditors", "Trust protecting beneficiaries from themselves", "Retirement trust", "Revocable trust"], correct_answer: "Trust where grantor is beneficiary, protected from creditors", explanation: "Domestic Asset Protection Trusts (in 19 states) let you create irrevocable trust, be beneficiary, and gain creditor protection. Controversial; offshore trusts stronger." },
  { category_id: 12, question_text: "Private foundations require 5% annual distributions.", question_type: "true_false", difficulty_level: "advanced", options: ["True", "False"], correct_answer: "True", explanation: "True! Private foundations must distribute 5% of assets annually for charitable purposes. Also pay 1-2% excise tax on investment income. Better than DAFs for multi-generational control." },
  { category_id: 12, question_text: "What is a beneficiary defective inheritor's trust (BDIT)?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Swap power allows low-basis asset swap", "Invalid trust structure", "Trust for disabled beneficiaries", "Retirement trust"], correct_answer: "Swap power allows low-basis asset swap", explanation: "BDITs allow beneficiaries to swap low-basis assets into trust to get step-up at grantor's death, while removing high-basis assets. Advanced income tax planning." },
  { category_id: 12, question_text: "What is a toggle GRAT?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["GRAT with flexible annuity payments", "Switchable trust", "Revocable GRAT", "Joint GRAT"], correct_answer: "GRAT with flexible annuity payments", explanation: "Toggle GRATs allow annuity payments in cash or in-kind, providing flexibility if trust assets are illiquid. Helpful for closely-held business interests." },
  { category_id: 12, question_text: "The Rule Against Perpetuities limits trust duration in most states.", question_type: "true_false", difficulty_level: "advanced", options: ["True", "False"], correct_answer: "False", explanation: "False! Many states abolished RAP, allowing perpetual dynasty trusts. Alaska, Delaware, Nevada, South Dakota popular for generation-skipping trusts. Some states limit to 90-1,000 years." },
  { category_id: 12, question_text: "What is sale to defective grantor trust?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Selling assets to IDGT at fair value to freeze estate", "Invalid transaction", "Prohibited transaction", "Charitable gift"], correct_answer: "Selling assets to IDGT at fair value to freeze estate", explanation: "Selling appreciating assets to IDGT for promissory note freezes estate value. Future appreciation accrues in trust, tax-free to you. No income tax on sale to your own trust." },
  { category_id: 12, question_text: "What is a directed trust?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Separate parties control investments and distributions", "Trust with specific instructions", "Testamentary trust", "Revocable trust"], correct_answer: "Separate parties control investments and distributions", explanation: "Directed trusts split trustee duties - administrative trustee handles paperwork, investment director manages assets, distribution director makes payment decisions. Provides specialization." },
  { category_id: 12, question_text: "Trust protectors can modify irrevocable trusts.", question_type: "true_false", difficulty_level: "advanced", options: ["True", "False"], correct_answer: "True", explanation: "True! Trust protectors (named in trust) can change trustees, modify terms for tax law changes, move to different state, or even decant trust. Adds flexibility to irrevocable trusts." },
  { category_id: 12, question_text: "What is trust decanting?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Transferring assets from one trust to another with better terms", "Closing a trust", "Trust tax payment", "Trust audit"], correct_answer: "Transferring assets from one trust to another with better terms", explanation: "Decanting (like pouring wine) moves assets from old trust to new trust with updated terms. Fixes drafting errors, adapts to law changes. Allowed in 30+ states." },
  { category_id: 12, question_text: "What is a qualified disclaimer trust?", question_type: "multiple_choice", difficulty_level: "advanced", options: ["Trust receiving disclaimed inheritance for tax planning", "Trust that failed IRS qualification", "Charitable trust", "Revocable trust"], correct_answer: "Trust receiving disclaimed inheritance for tax planning", explanation: "Surviving spouse can disclaim assets to bypass or QTIP trust, optimizing estate tax planning post-death. Provides flexibility based on actual tax situation at death." }
];

console.log('Uploading Category 12: Estate Planning...');
await supabase.from('quiz_questions').insert(CATEGORY_12_ESTATE);
console.log('✅ Category 12 complete: 70 questions');
